server:
  port: 8765

spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
         max-wait: 1
         max-active: 8
         max-idle: 500
         min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/1906yhq?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    allow-session-override: true


 xxl:
   job:
     admin:
       #调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。
       #执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
       addresses: http://127.0.0.1:8080/xxl-job-admin
 
     #分别配置执行器的名称、ip地址、端口号
     #注意：如果配置多个执行器时，防止端口冲突
     executor:
       appname: executorDemo
       ip: 127.0.0.1
       port: 9999
 
       #执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
       logpath: /data/applogs/xxl-job/jobhandler
       #执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
       #-1表示永不删除
       logretentiondays: -1


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
 # type-aliases-package: com.mr.mradmin.entity
