server:
  port: 8762

spring:
  redis:
    host: localhost
    database: 0
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/1906yhq?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    allow-session-override: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
 # type-aliases-package: com.mr.mradmin.entity
