server:
  port: 8766
spring:
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    allow-session-override: true
